development:
  dialect: "mysql"
  database: "web_app_development"
  host: "localhost"
  port: "3306"
  user: "dbdesigner"
  password: "model"

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://dbdesigner:model@(localhost:3306)/web_app_test?parseTime=true&multiStatements=true&readTimeout=1s"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://dbdesigner:model@(localhost:3306)/web_app_production?parseTime=true&multiStatements=true&readTimeout=1s"}}